deployment templates

diff --git a/bin/iac b/bin/iac
--- a/bin/iac
+++ b/bin/iac
@@ -220,26 +220,28 @@ _showHashedDeplLabels()
   fi
 }
 
-showTemplate()
+
+# $1: name
+# $2: type key
+_showElement()
 {
-  local i
-  local a=( )
-  local p="${tmplDefs[$1]}"
-  if [ -z "$p" ]; then
-    Error "deployment template $1 not found"
-  fi
-  color_confirm "deployment template $1"
+  local p
+  local t
+  local c
+
+  eval p="\"\${${2}Defs[\"\$1\"]}\""
+
   color_found "  path: $(norm_path "$p")"
 
-  _showHashedList "$1" tmplDCtxs "descriptor context"
-  _showHashedList "$1" tmplDStubs "descriptor stubs" norm_path
+  _showHashedList "$1" ${2}DCtxs "descriptor context"
+  _showHashedList "$1" ${2}DStubs "descriptor stubs" norm_path
 
-  local t="${tmplTmpls[$1]}"
+  eval t="\"\${${2}Tmpls[\"\$1\"]}\""
   if [ -n "$t" ]; then
     color_title "  templates:" 
   fi
   while [ -n "$t" ]; do
-    p="${tmplDefs[$t]}"
+    p="${tmplDefs["$t"]}"
     if [ -z "$p" ]; then
       color_warn "  - $t (undefined)"
     else
@@ -247,7 +249,8 @@ showTemplate()
     fi
     t="${tmplTmpls[$t]}"
   done
-  local c="${tmplComps[$1]}"
+
+  eval c="\"\${${2}Comps[\"\$1\"]}\""
   if [ -z "$c" ]; then
     color_warn "no component declared"
   else
@@ -260,18 +263,34 @@ showTemplate()
     _showHashedList "$c" compCtxs "component context"
   fi
 
-  _showHashedList "$1" tmplInfos "configurations" norm_path
+  _showHashedDeplList "$1" ${2}Reqs "requires"
+  if ! _equals_array "$1" ${2}Reqs ${2}EReqs; then
+    _showHashedDeplList "$1" ${2}EReqs "requires (effective)"
+  fi
+  _showHashedDeplList "$1" ${2}Glmps "glimpses"
+  if ! _equals_array "$1" ${2}Glmps ${2}EGlmps; then
+    _showHashedDeplList "$1" ${2}EGlmps "glimpses (effective)"
+  fi
 
-  _showHashedDeplList "$1" tmplReqs "requires"
-  _showHashedDeplList "$1" tmplEReqs "requires (effective)"
-  _showHashedDeplList "$1" tmplGlmps "glimpses"
-  _showHashedDeplList "$1" tmplEGlmps "glimpses (effective)"
+  _showHashedList "$1" ${2}Incls " includes"
 
-  _showHashedList "$1" tmplIncls " includes"
+  _showHashedDeplLabels "$1" ${2}Labels "effective imports"
+  _showHashedList "$1" ${2}Ctxs "context"
+  if ! _equals_array "$1" ${2}Ctxs ${2}ECtxs; then
+    _showHashedList "$1" ${2}ECtxs "effective context"
+  fi
+}
 
-  _showHashedDeplLabels "$1" tmplLabels "effective imports"
-  _showHashedList "$1" tmplCtxs "context"
-  _showHashedList "$1" tmplECtxs "effective context"
+showTemplate()
+{
+  local i
+  local a=( )
+  local p="${tmplDefs[$1]}"
+  if [ -z "$p" ]; then
+    Error "deployment template $1 not found"
+  fi
+  color_confirm "deployment template $1"
+  _showElement "$1" tmpl
 }
 
 showDeployment()
@@ -291,38 +310,12 @@ showDeployment()
   else
     color_confirm "deployment definition $1"
   fi
-  color_found "  path: $(norm_path "$p")"
   if [ ! ${deplActive[$1]:+set} ]; then
     color_red "  INACTIVE"
   fi
-
-  _showHashedList "$1" deplDCtxs "descriptor context"
-  _showHashedList "$1" deplDStubs "descriptor stubs" norm_path
-
-  local c="${deplComps[$1]}"
-  if [ -z "$c" ]; then
-    color_warn "no component declared"
-  else
-    p="${compDefs[$c]}"
-    if [ -z "$p" ]; then
-      color_warn "  component: $c (undefined)"
-    else
-      color_found "  component: $c ($(norm_path "$p"))"
-    fi
-
-    _showHashedList "$c" compCtxs "component context"
-  fi
-
   _showHashedList "$1" deplInfos "configurations" norm_path
-
-  _showHashedDeplList "$1" deplReqs "requires"
-  _showHashedDeplList "$1" deplGlmps "glimpses"
-
-  _showHashedList "$1" deplIncls " includes"
-
-  _showHashedDeplLabels "$1" deplLabels "imports"
-  _showHashedList "$1" deplCtxs "context"
-  _showHashedList "$1" deplStubs "stubs" norm_path
+  _showElement "$1" depl
+  _showHashedList "$1" deplStubs "effective stubs" norm_path
 }
 
 
diff --git a/lib/iacman b/lib/iacman
--- a/lib/iacman
+++ b/lib/iacman
@@ -113,6 +113,15 @@ require_deplname()
   fi
 }
 
+require_tmplname()
+{
+  if [ -n "$1" ]; then
+    echo "$1"
+  else
+    require_default_tmplname template name required
+  fi
+}
+
 deplname_from_args()
 {
   require_default_deplname "not in a deployment -> use option -d to specify deployment name"
@@ -142,6 +151,23 @@ require_default_deplname()
       else
         Error "${ERRCTX}${ERRCTX:+: }$@"
       fi
+    fi
+  fi
+}
+
+# $@: error message
+require_default_tmplname()
+{
+  if [ -n "$TNAME" ]; then
+    echo "$TNAME"
+  else
+    local d
+    d="$(require_default_deplname "$@")"  
+    local t="${deplTmpls["$d"]}"
+    if [ -n "$t" ]; then
+      echo "$t"
+    else
+      Error "${ERRCTX}${ERRCTX:+: }$@"
     fi
   fi
 }
@@ -494,6 +520,7 @@ lookupStub()
      fi
   fi
 
+  lookupTemplateStubs "${deplTmpls[$1]}" "$2"
   
   _get_array a "$1" deplIncls || true
   for i in "${a[@]}"; do
@@ -501,6 +528,20 @@ lookupStub()
   done
 
   _lookupTree "$1" "$2" "${deplDefs[$1]}" "/" "$DIR_DEPLOYMENTS/$1" "$DIR_CONFIG"
+}
+
+# $1: template name
+# $2: context
+# $3+ ref history
+lookupTemplateStubs()
+{
+  if [ -n "$1" ] && ! contains "$1" "${@:3}"; then
+    lookupTemplateStubs "${tmplTmpls[$1]}" "$2" "$1" "${@:3}"
+    local dt="${tmplDefs["$1"]}"
+    if [ -n "$dt" ]; then
+      _filter_file "$dt/$2" || true
+    fi
+  fi
 }
 
 # $1: element name
@@ -914,6 +955,7 @@ setupComponent()
 # $3: type key
 # $4: type name 
 # $5+: template history
+# -> def
 _setupElement()
 {
   local a_n="$1"
@@ -967,7 +1009,7 @@ _setupElement()
         _setupTemplate "$tmpl" "${@:5}" 
         debug " using template $tmpl"
         eval "${a_k}Tmpls[\"\$a_n\"]=\"\$tmpl\""
-        eval "comp=\"\${${a_k}Comps[\"\$tmpl\"]}\""
+        comp="${tmplComps["$tmpl"]}"
         if [ -z "$comp" ]; then
           log warn " no component defined for $a_t $a_n because template $tmpl defines no component"
         fi
@@ -988,8 +1030,9 @@ _setupElement()
     debug " component contexts: ${ctxs[@]}"
   fi
 
+  local croot
   if [ -n "$comp" ]; then
-    local croot="${compDefs["$comp"]}"
+    croot="${compDefs["$comp"]}"
     if [ -z "$croot" ]; then
       log warn " component $comp for $a_t $a_n not defined"
     fi
@@ -1081,6 +1124,13 @@ _setupElement()
   set_array res uniq "${ctxs[@]}" "${res[@]}"
   debug " effective context ${res[@]}"
   _set_array "$a_n" ${3}ECtxs "${res[@]}"
+
+  _handleSetup_$a_k
+}
+
+_handleSetup_tmpl()
+{
+  true
 }
 
 # $1: name
@@ -1100,11 +1150,38 @@ _setupTemplate()
     return
   fi
   tmplDone["$1"]=X
+
   _setupElement "$1" $FILE_TEMPLATE tmpl "deployment template" "$@"
 }
 
 # $1: depl name
 setupDeployment()
+{
+  _setupElement "$1" $FILE_DEPLOYMENT depl "deployment definition"
+}
+
+_handleSetup_depl()
+{
+  local active="$(get_yaml_field - .active <<<"$def")"
+  if [ -z "$active" -o "$active" == true ]; then
+    active=X
+  else 
+    active=
+  fi
+
+  deplActive["$a_n"]="$active"
+  if [ -n "$croot" ]; then
+    deplCommon["$a_n"]="$(_commonRoot "$croot" "$root")"
+  else
+    deplCommon["$a_n"]=""
+  fi
+  local stubs=( )
+  lookupStubs "$a_n"  "${res[@]}"
+  _set_array "$a_n" deplStubs "${stubs[@]}"
+}
+
+# $1: depl name
+OLDsetupDeployment()
 {
   local ctxs=( )
   local stubs=( )
@@ -1115,6 +1192,22 @@ setupDeployment()
 
   debug " analyse descriptor..."
   local def="$(cat "$root/$FILE_DEPLOYMENT")"
+
+  _get_yaml_list '.["descriptor-context"][]' <<<"$def"
+  debug "found descriptor context: ${res[@]}"
+  _set_array "$1" deplDCtxs "${res[@]}"
+  if [ ${#res[@]} -gt 0 ]; then
+    lookupConfigs "$1" "$root" "${res[@]}"
+    _set_array "$1" deplDStubs "${stubs[@]}"
+    if [ ${#stubs[@]} -gt 0 ]; then
+      if [ -n "${opts[spiff]+x}" ]; then
+        log info spiff merge "$root/$FILE_DEPLOYMENT" "${stubs[@]}"
+      fi
+      def="$(spiff merge - "${stubs[@]}" <<<"$def" || Error "descriptor processing for $1 failed")"
+    fi
+  else
+    _set_array "$1" deplDStubs
+  fi
 
   local comp="$(get_yaml_field - .component <<<"$def")"
   if [ -z "$comp" ]; then
@@ -1132,22 +1225,6 @@ setupDeployment()
     fi
   fi
   deplComps[$1]="$comp"
-
-  _get_yaml_list '.["descriptor-context"][]' <<<"$def"
-  debug "found descriptor context: ${res[@]}"
-  _set_array "$1" deplDCtxs "${res[@]}"
-  if [ ${#res[@]} -gt 0 ]; then
-    lookupStubs "$1"  "${res[@]}"
-    _set_array "$1" deplDStubs "${stubs[@]}"
-    if [ ${#stubs[@]} -gt 0 ]; then
-      if [ -n "${opts[spiff]+x}" ]; then
-        log info spiff merge "$root/$FILE_DEPLOYMENT" "${stubs[@]}"
-      fi
-      def="$(spiff merge - "${stubs[@]}" <<<"$def" || Error "descriptor processing for $1 failed")"
-    fi
-  else
-    _set_array "$1" deplDStubs
-  fi
 
   local active="$(get_yaml_field - .active <<<"$def")"
   if [ -z "$active" -o "$active" == true ]; then
@@ -1224,6 +1301,7 @@ setupDeployment()
   set_array res uniq "${ctxs[@]}" "${res[@]}"
   debug " effective context ${res[@]}"
 
+  warn lookup $1: "${res[@]}"
   lookupStubs "$1"  "${res[@]}"
   _set_array "$1" deplStubs "${stubs[@]}"
 }
