scripts + cmdline

diff --git a/bin/lm b/bin/lm
--- a/bin/lm
+++ b/bin/lm
@@ -8,6 +8,13 @@ source "$SCRIPT_DIR/../lib/lsman"
 ###########################################################################
 
 ########################
+# lib
+CMD_lib()
+{
+  echo "$(dirname "$SCRIPT_DIR")/lib/boshman"
+}
+
+########################
 # ls
 CMD_ls()
 {
@@ -45,11 +52,16 @@ CMD_ls()
 showDeployment()
 {
   local i
+  local a=( )
   local p="${deplDefs[$1]}"
   if [ -z "$p" ]; then
     Error "deployment $1 not found"
   fi
-  found "deployment $1"
+  if [ -f "$p/$FILE_DEPLOYMENT" ]; then
+    found "deployment definition $1"
+  else
+    found "deployment configuration $1"
+  fi
   found "  path: $(norm_path "$p")"
 
   local c="${deplComps[$1]}"
@@ -62,9 +74,16 @@ showDeployment()
     else
       found "  component: $c ($(norm_path "$p"))"
     fi
+
+    _get_array a "$c" compCtxs || true
+    if [ ${#a[@]} -gt 0 ]; then
+      found "  component context:"
+      for i in "${a[@]}"; do
+        found "  - $i"
+      done
+    fi
   fi
 
-  local a=( )
   _get_array a "$1" deplInfos || true
   if [ ${#a[@]} -gt 0 ]; then
     found "  configurations:"
@@ -114,16 +133,24 @@ showComponent()
   found "component $1"
   found "  path: $(norm_path "$p")"
   
-  local f=
-  for i in "${!deplComps[@]}"; do
-    if [ "${deplComps[$i]}" == "$1" ]; then
+  _get_array a "$1" compCtxs || true
+  if [ ${#a[@]} -gt 0 ]; then
+    found "  context:"
+    for i in "${a[@]}"; do
+      found "  - $i"
+    done
+  fi
+
+  get_component_deployments "$1" | (
+    local f=
+    while IFS='' read -r d; do
       if [ -z "$f" ]; then
         found "  deployments"
         f=X
       fi
-      found "  - $i ($(norm_path "${deplDefs[$1]}"))"
-    fi
-  done
+      found "  - $d ($(norm_path "${deplDefs[$d]}"))"
+    done
+  )
 }
 
 showModule()
@@ -149,17 +176,10 @@ CMD_show()
 
   if [ $# -eq 0 ]; then
     if [ -n "$CROOT" ]; then
-      found "component $CNAME"
       showComponent "$CNAME"
     fi
     if [ -n "$DROOT" ]; then
-      if [ -f "$DROOT/$FILE_DEPLOYMENT" ]; then
-        found "deployment definition for $DNAME"
-        showDeployment "$DNAME"
-      else
-        found "deployment config for $DNAME"
-        showDeployment "$DNAME"
-      fi
+      showDeployment "$DNAME"
     fi
     if [ -z "$CROOT" -a -z "$DROOT" -a -n "$MROOT" ]; then
       if [ -z "$MNAME" ]; then
@@ -211,12 +231,10 @@ CMD_closure()
   cacheAll
 
   local t
-  local n="${1:-$DNAME}"
-  if [ -z "$n" ]; then
-    Error "${ERRCTX}${ERRCTX:+: }deployment name missing"
-  fi
-  t="$(require_deployment "$1")"
-  info "generating dependency closure for $n"
+  local n
+  n="$(require_deplname "$1")"
+  t="$(require_deployment "$n")"
+  log info "generating dependency closure for $n"
 
   local a=( )
   if ! _closure a "$n"; then
@@ -236,14 +254,12 @@ CMD_exports()
   cacheAll
 
   local t
-  local n="${1:-$DNAME}"
-  if [ -z "$n" ]; then
-    Error "${ERRCTX}${ERRCTX:+: }deployment name missing"
-  fi
-  t="$(require_deployment "$1")"
+  local n
+  n="$(require_deplname "$1")"
+  t="$(require_deployment "$n")"
   mkdir -p "$TMP"
-  info "generating exports for $n"
-  generate_exports "$1" "$TMP"
+  log info "generating exports for $n"
+  generate_exports "$n" "$TMP"
 }
 
 ########################
@@ -255,14 +271,56 @@ CMD_manifest()
   cacheAll
 
   local t
-  local n="${1:-$DNAME}"
-  if [ -z "$n" ]; then
-    Error "${ERRCTX}${ERRCTX:+: }deployment name missing"
-  fi
-  t="$(require_deployment "$1")"
+  local n
+  n="$(require_deplname "$1")"
+  t="$(require_deployment "$n")"
   mkdir -p "$TMP"
-  info "generating manifest for $n"
-  generate_manifest "$1" "$TMP"
+  log info "generating manifest for $n"
+  generate_manifest "$n" "$TMP"
+}
+
+########################
+# script execution
+
+exec_script()
+{
+  setupEnv
+  cacheAll
+
+  local t
+  local n
+  local s="$1"
+  shift
+  n="$(deplname_from_args)"
+  t="$(require_deployment "$n")"
+  local p="$(get_script "$n" "$DIR_SCRIPTS/$s")"
+  if [ -z "$p" ]; then
+    Error "${ERRCTX}${ERRCTX:+: }script '$s' not found for '$n'"
+  fi
+  "$p" "$@"
+}
+
+CMD_script()
+{
+  if [ $# -lt 1 ]; then
+    Error "${ERRCTX}${ERRCTX:+: }script name missing"
+  fi
+  exec_script "$@"
+}
+
+CMD_prepare()
+{
+  exec_script prepare "$@"
+}
+
+CMD_plan()
+{
+  exec_script plan "$@"
+}
+
+CMD_deploy()
+{
+  exec_script deploy "$@"
 }
 
 ###########################################################################
@@ -283,8 +341,33 @@ fi
 # help
 ###########################################################################
 
-if [ -z "$cmd" -o "$1" == help -o "$1" == "--help" -o "$1" == "-help" ]; then
-  echo lsman
+if [ -z "$cmd" -o "$cmd" == help -o "$cmd" == "--help" -o "$cmd" == "-help" ]; then
+  found lsman - landscape management tool
+  title "lm/lsman [<options>] <command> [<args>]"
+  found
+  found "Options:"
+  found "  -q         quiet"
+  found "  -D         debug"
+  found "  -d <name>  deployment name"
+  found
+  found "Commands:"
+  found "  ls [<dir>]                                  list landscape/module structure"
+  found "  show [[component|deployment|module] <name>] details for dedicated element"
+  found "  closure [<name>]                            dependency closure"
+  found 
+  found "Handle scripts provided by component for deployments:"
+  found "  script <name>  <args>         execute arbitrary script for deployment"
+  found "  prepare                       execute prepare script"
+  found "  manifest                      generate manifest"
+  info  "                                context provided by lm and passed as argument"
+  info  "                                this script is defaulted by using"
+  info  "                                the context as manifest."
+  found "  exports                       generate exports"
+  info  "                                context provided by lm and passed as argument"
+  info  "                                this script is defaulted by generating"
+  info  "                                the manifest and reading the exports section."
+  found "  plan                          execute plan script"
+  found "  deploy                        execute deploy script"
   exit 0
 fi
 
@@ -293,17 +376,13 @@ fi
 ###########################################################################
 declare -g -A opts
 declare -g -A params
-params=( [lib]= [q]=quiet [D]=debug )
+params=( [q]=quiet [D]=debug [d]="=deployment" )
 OPT_parse_options params opts "$@"
 shift $(( _cnt - 1 ))
 
 #
 # support boshman based scripts by providing path to source boshman
 #
-if [ ${opts[lib]+set} ]; then
-  echo "$(dirname "$SCRIPT_DIR")/lib/boshman"
-  exit 0
-fi
 if [ ${opts[quiet]+set} ]; then
   QUIET=X
 fi
@@ -312,7 +391,7 @@ if [ ${opts[debug]+set} ]; then
 fi
 
 
-CMDS=( ls show closure exports manifest )
+CMDS=( show closure exports manifest script ls prepare plan deploy lib )
 cmd="$(resolve_shortcut "$cmd" "${CMDS[@]}")"
 
 execute_command "$cmd" CMD_ "${CMDS[*]}" "$@"
