fix proxy handling

diff --git a/plugins/terraform/actions/prepare b/plugins/terraform/actions/prepare
--- a/plugins/terraform/actions/prepare
+++ b/plugins/terraform/actions/prepare
@@ -45,7 +45,7 @@ set -o pipefail
 
 Error()
 {
-  echo "Error: $*" 2>&1
+  echo "Error: $*" >&2
   exit 1
 }
 
@@ -182,6 +182,7 @@ fi
 if [ -z "$IAC_QUIET" ]; then
   echo "--> action $CMD $@" >&2
 fi
+
 case "$CMD" in
 
   prepare)         do_prepare "$@";;
